// DO NOT EDIT THIS FILE

#ifndef _WAMI_FLASH_H_
#define _WAMI_FLASH_H_

#include "wami_params.h"

/* Shorten the name of the Debayer pad for readability */
#define PAD WAMI_FLASH_PAD

void wami_flash(
    rgb_pixel flashed[WAMI_FLASH_IMG_NUM_ROWS-2*PAD][WAMI_FLASH_IMG_NUM_COLS-2*PAD],
    u16 (* const bayer)[WAMI_FLASH_IMG_NUM_COLS]);

#endif
